---
change_branch: "{{ git_branch_prefix | default('fw-change') }}/{{ request.number | default('CHGXXXX') }}"
propose_git_user_name: "aap-bot1"
propose_git_user_email: "300886673+aap-bot1@users.noreply.github.com"
