---
- name: Commit firewall config
  hosts: pa_fw
  connection: local

  tasks:
    - name: Commit configuration
      paloaltonetworks.panos.panos_commit_firewall:
        provider: "{{ panos_provider }}"
